apiVersion: batch/v1
kind: Job
metadata:
  name: collectstatic
  namespace: mytardis
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      restartPolicy: Never
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
        supplementalGroups:
        - 418
        - 1931
      containers:
      - name: go
        image: :[dockerImageFullNameTag]
        command: ["/bin/sh", "-c", "python3 manage.py collectstatic --noinput"]
        volumeMounts:
          - name: settings
            mountPath: /app/tardis/settings.yaml
            subPath: settings.yaml
          - name: nfs-static-files
            mountPath: /srv/static
      volumes:
      - name: settings
        configMap:
          name: mytardis
      - name: nfs-static-files
        persistentVolumeClaim:
          claimName: nfs-static-files
