apiVersion: batch/v1 
kind: Job 
metadata:
  name: create-es-index
  namespace: mytardis
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - name: go
        image: [dockerImageFullNameTag]
        imagePullPolicy: Always
        command: ["/bin/sh", "-c", "python3 manage.py search_index -f --rebuild"]
        volumeMounts:
          - name: settings
            mountPath: /app/tardis/settings.yaml
            subPath: settings.yaml
        resources:
          limits:
            cpu: "4"
            memory: "8Gi"
          requests:
            cpu: "4"
            memory: "8Gi"
      restartPolicy: Never
      volumes:
      - name: settings
        configMap:
          name: mytardis

