apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
  namespace: mytardis
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - name: go
        image: :[dockerImageFullNameTag]
        command: ["/bin/sh", "-c", "python3 manage.py migrate"]
        volumeMounts:
          - name: settings
            mountPath: /app/tardis/settings.yaml
            subPath: settings.yaml
      restartPolicy: Never
      volumes:
      - name: settings
        configMap:
          name: mytardis
